apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: kubernetes-manifest-pipeline
spec:
  params:
    - description: URL of the Git repository containing K8s manifests
      name: git-url
      type: string
    - default: main
      description: Git revision to check out
      name: git-revision
      type: string
    - default: manifests/
      description: Path to the Kubernetes manifests in the repository
      name: manifest-path
      type: string
    - default: 1.24.0
      description: Kubernetes version to validate against
      name: kubernetes-version
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
    - name: validate
      params:
        - name: manifest-path
          value: $(params.manifest-path)
        - name: kubernetes-version
          value: $(params.kubernetes-version)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: kubeval-validator
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: lint
      params:
        - name: manifest-path
          value: $(params.manifest-path)
      runAfter:
        - validate
      taskRef:
        kind: Task
        name: kube-linter
      workspaces:
        - name: source
          workspace: shared-workspace
    - name: deploy
      params:
        - name: manifest-path
          value: $(params.manifest-path)
      runAfter:
        - lint
      taskRef:
        kind: Task
        name: oc-apply
      workspaces:
        - name: source
          workspace: shared-workspace
  workspaces:
    - name: shared-workspace
