# php-app-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: php-app-html
  labels:
    app: php-app
data:
  index.php: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>PHP Demo on OpenShift</title>
        <style>
            body { font-family: Arial, sans-serif; margin: 40px; }
            .container { max-width: 800px; margin: 0 auto; }
            .box { background: #f5f5f5; padding: 20px; border-radius: 5px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Welcome to PHP on OpenShift!</h1>
            <div class="box">
                <?php
                    echo "<p><strong>Hostname:</strong> " . gethostname() . "</p>";
                    echo "<p><strong>Message:</strong> " . getenv('DISPLAY_MESSAGE') . "</p>";
                    echo "<p><strong>Time:</strong> " . date('Y-m-d H:i:s') . "</p>";
                ?>
            </div>
        </div>
    </body>
    </html>
