apiVersion: v1
kind: ConfigMap
metadata:
  name: php-app-config
data:
  index.php: |
    <?php
    echo "<p>Message: " . ($_ENV['MESSAGE'] ?? '(not set)') . "</p>";
    echo "<p>Hostname: <b>" . gethostname() . "</b></p>";
    ?>
    
