# php-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: registry.access.redhat.com/ubi9/php-82  # Red Hat UBI PHP 8.2
        ports:
        - containerPort: 8080
        env:
        - name: DISPLAY_MESSAGE
          value: "Hello from OpenShift PHP Pod!"
        volumeMounts:
        - name: html-volume
          mountPath: /opt/app-root/src
      volumes:
      - name: html-volume
        configMap:
          name: php-app-html
      securityContext:
        runAsUser: 1001  # UBI default non-root user
        fsGroup: 0
