# php-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: ghcr.io/php:8.2-apache
        ports:
        - containerPort: 80
        env:
        - name: APP_MESSAGE
          value: "Hello HPE!"
        volumeMounts:
        - name: html-volume
          mountPath: /var/www/html
        securityContext:
          runAsUser: 1000  # Required for OpenShift compatibility
          allowPrivilegeEscalation: false
      volumes:
      - name: html-volume
        configMap:
          name: php-app-html
      securityContext:
        fsGroup: 1000  # Ensures file permissions work
