# php-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: quay.io/startx/php
        ports:
        - containerPort: 8080
        env:
        - name: APP_MESSAGE
          value: "Hello HPE!"
        - name: DISPLAY_MESSAGE
          value: "Deployed using ArgoCD Gitops"
        volumeMounts:
        - name: html-volume
          mountPath: /app
        securityContext:
          runAsUser: 1000  
          allowPrivilegeEscalation: false
      volumes:
      - name: html-volume
        configMap:
          name: php-app-html
      securityContext:
        fsGroup: 1000  # Ensures file permissions work
